// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CarsWebAppML.Model
{
    public class ModelInput
    {
        [ColumnName("BrandModel"), LoadColumn(0)]
        public string BrandModel { get; set; }


        [ColumnName("Year"), LoadColumn(1)]
        public float Year { get; set; }


        [ColumnName("Fuel"), LoadColumn(2)]
        public string Fuel { get; set; }


        [ColumnName("HorsePower"), LoadColumn(3)]
        public float HorsePower { get; set; }


        [ColumnName("Mileage"), LoadColumn(4)]
        public float Mileage { get; set; }


        [ColumnName("Price"), LoadColumn(5)]
        public float Price { get; set; }


    }
}
